version: "3.9"

services:
  app:
    image: flask_speaker_verification
    ports:
      - 7070:7070
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         device_ids: ['0']
    #         capabilities: [gpu]
    network_mode: "host"